"""create initial tables

Revision ID: 17b87c431322
Revises: 
Create Date: 2025-02-21 19:18:41.916924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b87c431322'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_package_extensions',
    sa.Column('deployment_package_id', sa.Integer(), nullable=False),
    sa.Column('prompt_template', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('deployment_package_id'),
    sa.UniqueConstraint('deployment_package_id')
    )
    op.create_table('scripts',
    sa.Column('student_deployment_id', sa.Integer(), nullable=False),
    sa.Column('raw_llm_response', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('scene_dialogue', sa.JSON(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('prompt_used', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_deployment_id')
    )
    op.create_table('videos',
    sa.Column('student_deployment_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('heygen_video_id', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('scripts')
    op.drop_table('deployment_package_extensions')
    # ### end Alembic commands ###
