"""Add callback id to video model

Revision ID: aa3dce0c2157
Revises: d308e67c4b3e
Create Date: 2025-03-18 13:29:24.707363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3dce0c2157'
down_revision: Union[str, None] = 'd308e67c4b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('callback_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'callback_id')
    # ### end Alembic commands ###
